# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('site_id', models.CharField(max_length=20, unique=True)),
                ('site_name', models.CharField(max_length=50)),
                ('river_basins', models.CharField(max_length=50)),
                ('river_name', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('safety_level', models.FloatField(null=True)),
                ('warning_level', models.FloatField(null=True)),
                ('crawl_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'site',
                'managed': False,
            },
        ),
    ]
